0-module task done
js-tasks-ru/jsbasic-20210420_inferno2106 pull request #1
Opened 2021-04-18 13:53 UTC by infernolik

Test task is done

2021-04-18 13:53 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-04-20 19:40 UTC, SinimaWath requested changes
Добро пожаловать на курс!

Здесь, на ГитХабе, я буду оставлять замечания
к твоим задачам

2021-04-20 19:40 UTC, SinimaWath commented on 0-module/1-task/index.js
> +sum(2,5) === 7;
Логгирование стоит убирать из дз.

2021-04-20 19:40 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return regex.test(name);
Круто, что знаешь про регулярки.

Только их всегда принято выносить в глобальную область видимости, в целях оптимизации:
```

const VALID_NAME_RE = /.../;

funcion isValid() {
 ....
}

```

2021-04-20 19:40 UTC, SinimaWath commented on 1-module/3-task/index.js
> +          : checked;
Тернарный оператор не принято использовать в таких случаях, когда надо выполнить присваивание.

Намного гармоничней и понятней здесь будет if

2021-04-20 19:40 UTC, SinimaWath commented on 1-module/4-task/index.js
> +          : false;
lowered.includes("1xbet") || lowered.includes("xxx") - в этой операции учавствуют только boolean: `boolean || boolean` - поэтому итоговое значение и так boolean, поэтому смысла в тернарном операторе нет и его можно убрать

2021-04-20 19:40 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  return newStr;
Можно переписать проще:

```
if (...) {
   return ...
}

return ...
```

else тут явно лишний

2021-04-21 17:25 UTC, SinimaWath requested changes

2021-04-21 17:25 UTC, SinimaWath commented on 0-module/1-task/index.js
> +sum(2,5);
Вообще убери вызовы функций, это может поломать тесты :) И в других задачах тоже

2021-04-21 17:25 UTC, SinimaWath commented on 1-module/2-task/index.js
> +let regex = /^[A-Za-z]{4,}$/;
Это тогда должен быть const - то есть неизменяемое значение. И в разработке глобальные константы обычно называют с капсом REGEX

2021-04-21 17:25 UTC, SinimaWath commented on 1-module/3-task/index.js
> +    checked = checked[0].toUpperCase() + checked.slice(1, 4);
`slice(1, 4)` - немного не корректно. А если в строке будет 20 букв? Нужно этот случай тоже поддержать, у slice есть возможность передавать только одно значение

2021-04-21 17:25 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
Обычно малое количество правил(меньше 4), можно лаконично уместить в return.

Это как раз тот случай

2021-04-21 17:25 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let lowered = str.toLowerCase();
это const, так как ты не изменяешь значение этой переменной

2021-04-21 17:25 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  return newStr;
Давай перепишем все таки вот так

2021-05-01 14:38 UTC, SinimaWath requested changes

2021-05-01 14:38 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (isFinite(salaries[i]) && salaries[i] != !0) sum += salaries[i];
не понял идею проверки: `salaries[i] != !0`, зачем она?

2021-05-01 14:38 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  for (let i in salaries) {
Для переменной i, стоит подобрать подходящее название. Здесь кажется, что i - это index,  но на самом деле это не так, for in - возвращает ключи

2021-05-01 14:38 UTC, SinimaWath commented on 2-module/2-task/index.js
> +  return false;
Давай упростим до одной строки: `return Object.entries`

2021-05-01 14:38 UTC, SinimaWath commented on 2-module/3-task/index.js
> +    this.second = +prompt("Enter second number");
По условию задачи first и second должны получается из аргументов функции read

2021-05-03 16:51 UTC, infernolik commented on 2-module/1-task/index.js
> +    if (isFinite(salaries[i]) && salaries[i] != !0) sum += salaries[i];
Если в объекте свойство isPayed будет поставлено в true, то при обходе значений в цикле true засчитается как +1 в итоговой сумме. Для этого сделал проверку

2021-05-03 17:05 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (isFinite(salaries[i]) && salaries[i] != !0) sum += salaries[i];
тогда правильно добавить, проверку typeof  ... === 'number'

2021-05-03 20:35 UTC, infernolik commented on 2-module/1-task/index.js
> +    if (isFinite(salaries[i]) && salaries[i] != !0) sum += salaries[i];
поправил, спасибо

2021-05-04 19:06 UTC, SinimaWath requested changes

2021-05-04 19:06 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map(obj => obj.name);
Давай используем деструкторизацию в аргументе функции для практики

2021-05-04 19:06 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Есть чуть более подходящие методы, давай перепишем вот на такую цепочку:
```
.filter
.map
.join
```

2021-05-05 16:27 UTC, infernolik commented on 3-module/1-task/index.js
> +  return users.map(obj => obj.name);
Не совсем понял как её тут можно вставить, попробовал так (в пуше с исправлениями)

2021-05-06 14:20 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map(obj => obj.name);
Имел ввиду вот так: `({ name }) => name`

2021-05-06 14:26 UTC, SinimaWath requested changes

2021-05-06 14:26 UTC, SinimaWath commented on 3-module/4-task/index.js
> +        // });
Давай уберем комментарии из кода, они тут лишние ;)

2021-05-06 14:26 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  console.log(filtered);
Тут немного лишний console.log, его тоже уберем

2021-05-06 19:02 UTC, infernolik commented on 3-module/5-task/index.js
> +  console.log(filtered);
Я тут запушил изменения в бранч без коммита, поэтому пуш 6622b96 не принимай пожалуйста.

2021-05-07 12:59 UTC, SinimaWath commented on 3-module/5-task/index.js
> +  console.log(filtered);
В гитхабе нельзя не принимать/принимать отдельные коммиты ( Только полностью ветку

2021-05-07 18:50 UTC, SinimaWath requested changes

2021-05-07 18:50 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  for (let i in salaries) {
Это надо поправить

2021-05-07 18:50 UTC, SinimaWath commented on 4-module/3-task/index.js
> +  })();
Немного не понимаю зачем тут нужны IIFE, давай просто сделаем 3 отдельные функции:
```
makeAvailable(tr);
specifyGender(tr);
lineThrough(tr);
```

2021-05-08 13:42 UTC, infernolik commented on 4-module/3-task/index.js
> +  })();
думал будет коряво выглядеть что объявляем функцию, а потом ещё три строки на вызов занимаем

2021-05-08 14:11 UTC, SinimaWath approved these changes

2021-05-08 14:12 UTC, merged